version: "3"
services:
  app:
    container_name: fastapi-app
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FASTAPI_APP=app.py
      - FASTAPI_RUN_HOST=0.0.0.0
    command: uvicorn app:app --host 0.0.0.0 --port 5000

  test:
    container_name: fastapi-test
    build: .
    volumes:
      - .:/app
    depends_on:
      - app
    command: pytest test_app.py
